string jsonAccountString = '{"Name":"JsonToApex", "Type":"Prospect", "AnnualRevenue":50}';
object ob = JSON.deserialize(jsonAccountString, Account.class);
Account acc = (Account)ob;
insert acc;

string jsonAccountString2 = '[{"Name":"HERO", "Type":"Prospect", "AnnualRevenue":50},{"Name":"Json To Apex HERO", "Type":"Prospect", "AnnualRevenue":50999999999}]';
Object ob1 = JSON.deserialize(jsonAccountString2, List<Account>.class);
List<Account> listacc = (List<Account>)ob1;
insert listacc;
System.debug('where is hero');//awdwad